name: 'Get Todo Comments'
description: 'Grab all the Todo comments added in a Pull Request'
inputs:
  github-token:  # should be secrets.GITHUB_TOKEN
    description: 'should be secrets.GITHUB_TOKEN'
    required: true
  asana-pat:  # Personal Access Token for Asana
    description: 'Personal Access Token for Asana'
    required: true
  asana-projects:  # String Array of Asana Project GIDs to add the new task
    description: 'String: Array of Asana Project IDs to add the new task. Add comman without space after each ID'
    required: true
  code-language:  # Code Language
    description: 'Coding language: Used to determine regex for looking for TODO comments. If not provided will get from Github Context. Can be default aslo.'
    required: false
runs:
  using: 'node20'
  main: 'index.js'